### ISSUE TITLE
Indented methods' CodeLens: documentation link doesn't work

### ISSUE THREAD

**Issue by AbsoluteWisp** [pixldev/Unity-Toolbox#2]
**BUG**  - CodeLens for indented methods adds extra %09 characters (tabulators) in the URL.

When the "Unity Event" CodeLens link is clicked, it leads to a broken URL.  
Example: When clicking on `Start`'s documentation link, it opened [https://docs.unity3d.com/ScriptReference/MonoBehaviour.%09Start.html](https://docs.unity3d.com/ScriptReference/MonoBehaviour.%09Start.html)  
It looks like there is an unwanted %09 (tabulator) character in the link. This only happens when the line with the method name is indented (suggesting a mistake in the URL cutter thing in the source), and is NOT exclusive to Start.  
  
Doesn't work:  
![image](https://user-images.githubusercontent.com/86200600/182408717-d00e914a-9ec5-4726-8eff-c34d1534723e.png)
Works:  
![image](https://user-images.githubusercontent.com/86200600/182409022-764955c9-de38-4582-a140-89a561201c33.png)

**Comment by maxsroka** [comment]
I can't reproduce the bug. I don't think it is necessary though, as I am currently rewriting the project.

**Comment by AbsoluteWisp** [comment]
Oh OK, it's not critical anyway.
