### ISSUE TITLE
Right click context menu that links to documentation

### ISSUE THREAD

**Issue by Festivejelly** [pixldev/Unity-Toolbox#5]
I think the right click context menu should link to the api documentation rather than the manual.

So for example if I right click on:

transform.Translate

It should take me here:
https://docs.unity3d.com/ScriptReference/30_search.html?q=transform.translate

Instead of here:
https://docs.unity3d.com/Manual/30_search.html?q=transform.Translate

Or maybe add an additional context menu for querying the api.

**Comment by maxsroka** [comment]
I've changed it in 1c56b0590e16712aae684b508004290d3fd953d6. Thanks!
