### ISSUE TITLE
Feature Request: Methods Tied to UI Callback Events

### ISSUE THREAD

**Issue by brikabrak** [pixldev/Unity-Toolbox#7]
Saw the work posted last month in getting prefab and scene uses listed in CodeLens for MonoBehaviours (which is awesome), and was wondering if there would be interest in getting similar functionality denoting which prefabs/scenes have certain methods tied to Insepctor Unity Event callbacks.

Currently in my code I have to denote in comments that a public method is for Inspector event tie-in. If I have the time I can play around in my fork to get it prototyped, but wanted to run it by project maintainer.

**Comment by maxsroka** [comment]
It's been on my to-do list for a long time. I'll do it when I have time. Thanks for the suggestion!
